[package]
name = "server"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bencher = { path = "../bencher" }
ron = "0.7"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.14", features = ["full"] }
