[package]
name = "bencher"
version = "0.0.0"
edition = "2021"

[dependencies]
futures = "0.3"
serde_json = "1.0"
shared = { path = "../shared" }
shiplift = "0.7"
thiserror = "1.0"
tokio = { version = "1.14", features = ["full"] }
